### ISSUE TITLE
would you mind adding a new release with the current changes on master?

### ISSUE THREAD

**Issue by schlichtanders** [beacon-biosignals/julia_pod#54]
Hi, thank you for all the work on packaging such julia dev environment for kubernetes.

I tried to package your package for nixos, which is how I realised that the latest master, where everything is moved to `julia_pod` subdirectory, does not yet have a release.

Would you mind creating a new release version for it?

**Comment by hannahilea** [comment]
Done---v0.3.0 and v0.3.1 are now tagged!
